
# Hyprland Configuration by "xZepyx"
# Maintainer : github.com/xZepyx


source = ~/.config/hypr/conf/defaults.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/envvars.conf
source = ~/.config/hypr/conf/colors.conf
source = ~/.config/hypr/conf/looks.conf
source = ~/.config/hypr/conf/startup.conf
source = ~/.config/hypr/conf/permissions.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/binds.conf
source = ~/.config/hypr/conf/animations/Slow.conf

# Float the PiP window, pin it (visible across workspaces), and keep it on top
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = noinitialfocus, title:^(Picture-in-Picture)$

misc {
    allow_session_lock_restore = true
  }

