# Default App Configuration (Adjust according to your liking.)


$terminal = kitty -e clifm
$fileManager = kitty -e clifm
$menu =  wofi --showyazi drun --allow-images
$texteditor = hx 
$browser = librewolf
